### ISSUE TITLE
Add ntfy self host configuration for UP

### ISSUE THREAD

**Issue by p1gp1g** [UnifiedPush/documentation#53]
An example of the server configuration with: 
* world writable subjects by default
* read access only for users
* steps to use the self hosted domain and the user for unifiedpush subject

It seems it is not clear how to restrict access a self hosted ntfy server used for unifiedpush. This would help.

**Comment by MayeulC** [comment]
Just writing down a couple things here, I might do a proper PR later:

* ntfy is world R/W by default, no need to adjust configuration
* To only allow users to read, you need to enable authentication:
  * Create a config.yml file if it doesn't exist (by default in `/etc/ntfy/config.yml` )
  * As the [ntfy doc says](https://ntfy.sh/docs/config/#example-private-instance), add the following to enable access control:
  ```yaml
  auth-file: "/var/lib/ntfy/user.db"
  auth-default-access: "deny-all" # Only users will be able to read or write topics
  ```
  (you might want to adjust the user DB path, especially if you use docker)
  * Restart ntfy server
  * Add a user:
    * `ntfy user add --role=admin someuser`
  * Pushers still need to be able to write to topics to send push notifications. Add a rule to make UnifiedPush topics (that start with "up") world-writeable:
    * `ntfy access '*' 'up*' write-only`

If you use docker, you might want to replace `ntfy` with `docker exec -it ntfy-container-name ntfy`
