### ISSUE TITLE
Animation for the landing page

### ISSUE THREAD

**Issue by p1gp1g** [UnifiedPush/documentation#61]

**Comment by karmanyaahm** [comment]
This looks amazing 🤩
but what do you think about doing two separate animations for distributors and apps? 
The most extreme interpretation (for the sake of idiot-proofing this): certain apps only work with certain distributors.

**Comment by p1gp1g** [comment]
+1 for the separated animation

Other remarks :
* I'd avoid NoProvider2Push (not production ready) (side note: We should update the doc about that)
* I'd add an unknown provider/app, for instance illustrated with a question mark
* I'd use the current NextPush logo for consistency (even if I really like this one) https://github.com/organizations/UP-NextPush
* Is there any possible issue using the firebase logo ? (and others)

**Comment by p1gp1g** [comment]
Here it is: ![nextpush](https://user-images.githubusercontent.com/31284753/176431050-ed5cbcf7-d83c-4a6f-9f8c-f83cdfb6faea.svg)

**Comment by karmanyaahm** [comment]
This is a basic demonstration of what I mean we could put on the website:

---

You can choose from a variety of distributors:
![up-explainer-1](https://user-images.githubusercontent.com/32671690/176482221-7bd67386-9cf0-471a-825f-7609fe1a7505.svg)  

And many apps currently support unifiedpush:
![up-explainer-2](https://user-images.githubusercontent.com/32671690/176482227-301a4446-092d-4720-a5bf-8392d49f4faf.svg)

---

It would need some modifications to make it look good, however.

**Comment by karmanyaahm** [comment]
How about this
![up-explainer-3](https://user-images.githubusercontent.com/32671690/176488097-5cefe909-c71a-4be1-9156-17419faaa2ba.svg)


The two sides not being in sync makes the animation a little less pleasing, but I personally feel like having the two out of sync demonstrates the point better (here, distributor is 5s and application is 2s), that the choice of application and distributor isn't linked.

**Comment by p1gp1g** [comment]
What about the same time but async ? It would make one distrib => 2 app and one app => 2 distrib

**Comment by MayeulC** [comment]
Another concept I spent some time on:

![illustration-v4](https://user-images.githubusercontent.com/3952726/176512153-947d9487-c1b0-402f-a7f3-0275ba57db91.svg)

---
Non-obvious changes:

* Made use of `<use>` to reuse icons, shaving a few kilobytes
* Used a background for `[matrix]`, which uses `fill:var(--body-background,grey)`

Gosh, that page is becoming heavy :P

**Comment by karmanyaahm** [comment]
One nitpick I have with this all-vertical design (this is already great, but if we are going for perfection here): 
It's a little difficult to mentally link the phone application to the app server since they are so far away and there's the distributor/provider scrolling in between them. That's something the original layout does better. 

Other than that, I think the continuous scrolling effect looks nice.

**Comment by karmanyaahm** [comment]
> I'll retrofit some `<use>` tags to lower the size a bit, I also added a "single connection" text, which helps understanding the whole, I think.

Can you make that please, whenever you have the time.
