### ISSUE TITLE
SVG Favicon not working

### ISSUE THREAD

**Issue by karmanyaahm** [UnifiedPush/documentation#63]
An svg favicon needs to be added to `static/favicon/favicon.svg`

@p1gp1g do you have the original logo file? I can't seem to find it

**Comment by p1gp1g** [comment]
Here it is : https://github.com/UnifiedPush/documentation/blob/e5d2f25d4b4d11413821b1f33bb71da6bb330c0b/static/brand.svg

**Comment by karmanyaahm** [comment]
Is there a colorful one like https://github.com/UnifiedPush/documentation/blob/e5d2f25d4b4d11413821b1f33bb71da6bb330c0b/static/favicon/favicon-32x32.png

**Comment by p1gp1g** [comment]
Here it is

![brand-2](https://user-images.githubusercontent.com/31284753/179683726-b5d10bbf-568e-4c7b-9f4a-f2a15cc7fc49.svg)
![brand-1](https://user-images.githubusercontent.com/31284753/179683729-0d718989-6da8-412b-99cb-3eea49e39f1f.svg)

**Comment by MayeulC** [comment]
Here are two redrawn versions, with the bell unskewed. I played with units and the viewbox to avoid decimal numbers, which shaves a few hundred bytes. I know I can have an OCD on this, but having a light logo is nice, especially for the favicon.


| 880 bytes         |  1576 bytes, no stroke     | 
|--------------|-----------|
| ![favicon](https://user-images.githubusercontent.com/3952726/180013257-15ef16d0-fe57-409a-b3df-0a55ededae14.svg)  | ![favicon-onlypath-2 2](https://user-images.githubusercontent.com/3952726/180013309-3b1c0575-de7b-4b36-b93f-861f1bbc37dc.svg)  |

The one on the left needs to be styled both with `fill` and `stroke`, the one on the right only with `fill`.
