### ISSUE TITLE
Add instructions to disable rate limit for ntfy

### ISSUE THREAD

**Issue by p1gp1g** [UnifiedPush/documentation#75]
When self-hosting ntfy, it may be needed to disable rate limite for the services used

Ping @karmanyaahm, since you've done it for the ansible-matrix-deploy

**Comment by karmanyaahm** [comment]
will do once I finish matrix ansible and get it working properly

--
Karmanyaah Malhotra

E: ***@***.*** ***@***.***)
W: https://karmanyaah.malhotra.cc/contact

**Comment by p1gp1g** [comment]
Done by default now iirc
